services:
  - type: web
    name: mood-music-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEMO_SECRET
        sync: false
      - key: DEBUG
        value: false
